version: "3.7"

services:
  arbitrader:
    image: antake/arbitrader:latest
    tty: true
    ports:
      - "5005:5005"
    volumes:
      - ${PWD}/application.yaml:/application.yaml
      - ${PWD}/.arbitrader:/.arbitrader
